site_name: Administración de Sistemas Operativos
site_url: https://javierhernadez81.github.io/aso2122/
use_directory_urls: false

nav:
  - "Inicio": "index.md"
  - "1.- Tools: Scripting y Docker":
    - "1.1- ShellScripting": "011_ShellScripting.md"
    - "1.2- PowerShell": "012_PowerShell.md"
#  - "": ""

theme:
  language: es
  favicon: imagenes/favicon.png
  name: "material"
  palette:
    primary: light blue
    accent: "Teal"
  font:
    text: Roboto
    code: Roboto Mono
  logo: "imagenes/logofp.png"
  features:
    - header.autohide
    - toc.integrate

extra:
  search:
    language: "es"
  social:
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/aitormedrano
    - icon: fontawesome/solid/envelope-square
      link: mailto:<fj.hernandez@edu.gva.es>
#  analytics:
#    provider: google
#    property: G-X6D0LR7TC8

plugins:
  - search

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - footnotes
  - meta
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 3

copyright: 2021-2022 Fº Javier Hernández - Licencia CC BY-NC-SA

